config/routes.rb
Rails.application.routes.draw do

  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  post "/graphql", to: "graphql#execute"
  resources :users
  resources :posts
  
  get '/posts/:id', to: 'posts#show'

  get '/about',   to: 'static#about'

  root 'static#home'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title,   presence: true, length: { maximum: 255  }
    validates :content, presence: true, length: { maximum: 4095 }
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  SHORT_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  before_save { self.email = email.downcase }

  validates :name,  presence: true,
                    length: { maximum: 63  }
  validates :email, presence: true,
                    length: { maximum: 255 },
                    format: { with: SHORT_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password

  validates :password,  presence: true,
                        length: { minimum: 8 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/graphql_controller.rb
class GraphqlController < ApplicationController
  def execute
    variables = ensure_hash(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    context = {
      # Query context goes here, for example:
      # current_user: current_user,
    }
    result = BlogSchema.execute(query, variables: variables, context: context, operation_name: operation_name)
    render json: result
  end

  private

  # Handle form data, JSON body, or a blank value
  def ensure_hash(ambiguous_param)
    case ambiguous_param
    when String
      if ambiguous_param.present?
        ensure_hash(JSON.parse(ambiguous_param))
      else
        {}
      end
    when Hash, ActionController::Parameters
      ambiguous_param
    when nil
      {}
    else
      raise ArgumentError, "Unexpected parameter: #{ambiguous_param}"
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    
  end

  def index
    @posts = Post.paginate(page: params[:page], per_page: 10)
  end
  
  def show
    @post = Post.find(params[:id].to_i(2))
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      #handle that shit
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def make_title(page_title = '')
        if !page_title.empty?
            page_title + " - "
        else
            page_title
        end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
  SHORT_DATE_REGEX = /\d{4}-\d{2}-\d{2} \d{2}:\d{2}/

  def short_date(long_date)
    SHORT_DATE_REGEX.match(long_date.to_s)
  end

  def short_post(long_post)
    if !long_post.nil?
      long_post.truncate(1024, seperator: ' ')
    end
  end

  def shorter_post(long_post)
    if !long_post.nil?
      long_post.truncate(512, seperator: ' ')
    end
  end
  
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user)
    gravatar_id  = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
      
end

app/views/layouts/_footer.html.erb
<% source_path = "https://github.com/J-Vaughan/Blog.git" %>

<footer class="footer">
  <small>
    Copyright &copy; <%= Date.today.year %> James Vaughan, powered by 
    <a href="https://rubyonrails.org">Ruby on Rails</a> and 
    <a href="https://getbootstrap.com">Bootstrap 4.0</a>.
  </small>
  <nav>
    <ul class="nav">
      <li class="nav-item"><%= link_to "About",       about_path  %></li>
      <li class="nav-item"><%= link_to "Source Code", source_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <%= link_to "James Vaughan", root_path, id: "logo", class: "h1 lobster" %>
    <nav>
      <ul class="nav">
        <li class="nav-item"><%= link_to "Home",      root_path,  class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "Posts",     posts_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "Projects",  '#',        class: "nav-link" %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= make_title( yield :title ) %>James Vaughan</title>
    <%= render 'layouts/rails_default' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="container">
      <%= yield %>

      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/posts/_recent.html.erb
<% Post.order(id: :desc).limit(3).each do |post| %>

  <div class="posts">
    <h4><%= link_to post.title, post_path(post.id.to_s(2)) %></h4>
    <p><%= short_post post.content %></p>


    <div class="row">
      <% if post.created_at != post.updated_at %>
        <small class="col-5 text-muted">
        Created <%= short_date(post.created_at) %>
        </small>
        <small class="col-5 text-muted center">
        Edited <%= short_date(post.updated_at) %>
        </small>
      <% else %>
        <small class="col-10 text-muted">
        Created <%= short_date(post.created_at) %>
        </small>
      <% end %>

      <small class="text-muted col-2">Id <%= post.id.to_s(2) %></small>
    </div>
  </div>

<% end %>

app/views/posts/index.html.erb
<% provide(:title, "Posts") %>

<h1 class="center">Posts</h1>

<% @posts.each do |post| %>
  <div class="posts">
    <h4><%= link_to post.title, post_path(post.id.to_s(2)) %></h4>
    <p><%= shorter_post post.content %></p>


    <div class="row">
      <% if post.created_at != post.updated_at %>
        <small class="col-4 text-muted">
        Created <%= short_date(post.created_at) %>
        </small>
        <small class="col-4 text-muted center">
        Edited <%= short_date(post.updated_at) %>
        </small>
      <% else %>
        <small class="col-8 text-muted">
        Created <%= short_date(post.created_at) %>
        </small>
      <% end %>

      <small class="text-muted col-4" id="post-id">Id <%= post.id.to_s(2) %></small>
    </div>
  </div>
<% end %>

<div class="container">
  <%= will_paginate %>
</div>

app/views/posts/show.html.erb
<%= provide(:title, @post.title) %>

<div class="posts">

  <h4><%= @post.title %></h4>
  <p><%= @post.content %></p>


  <div class="row">

    <% if @post.created_at != @post.updated_at %>

      <small class="col-4 text-muted">
      Created <%= short_date(@post.created_at) %>
      </small>
      <small class="col-4 text-muted center">
      Edited <%= short_date(@post.updated_at) %>
      </small>

    <% else %>

      <small class="col-8 text-muted">
      Created <%= short_date(@post.created_at) %>
      </small>

    <% end %>

    <small class="text-muted col-4" id="post-id">Id <%= @post.id.to_s(2) %></small>

  </div>

</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<h1 class="center">Sign up</h1>

<div class="row" id="newcenterformfuckyou">
  <div>
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h2>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h2>
      <h5>
        Recognition:
        <%= @user.karma %>
      </h5>
    </section>
  </aside>
</div>